import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'transforms-3d/card-flip',
  title: 'Card flip',
  categoryId: 'transforms-3d',
  difficulty: 'novice',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 15,
  tags: ['3d', 'rotateY', 'backface-visibility', 'perspective'],
  brief: [
    'Two faces, one card. Right now they are stacked flat and the back sits on top.',
    '',
    'Make the card flip in 3D on hover: give the scene `perspective`, let the card',
    '`transform-style: preserve-3d`, pre-rotate the back face 180° with `backface-visibility: hidden`',
    'on both faces, and transition the card to `rotateY(180deg)` over roughly 600ms.',
  ].join('\n'),
  goals: [
    'Hovering the scene flips the card 180° around the Y axis with a transition of roughly 600ms.',
    'The flip happens in real 3D: the scene supplies `perspective`, and the card preserves 3D for its children.',
    'Each face hides its reverse side with `backface-visibility: hidden`, and the back face is pre-rotated 180° so it reads correctly when shown.',
  ],
  starter: {
    'index.html': [
      '<div class="scene">',
      '  <div class="card">',
      '    <div class="face front">Front</div>',
      '    <div class="face back">Back</div>',
      '  </div>',
      '</div>',
      '',
    ].join('\n'),
    'styles.css': [
      '.scene {',
      '  width: 180px;',
      '  height: 240px;',
      '}',
      '',
      '.card {',
      '  position: relative;',
      '  width: 100%;',
      '  height: 100%;',
      '}',
      '',
      '/* Flip .card to rotateY(180deg) when .scene is hovered. */',
      '',
      '.face {',
      '  position: absolute;',
      '  inset: 0;',
      '  display: grid;',
      '  place-items: center;',
      '  border-radius: 12px;',
      '  font: 600 18px/1 system-ui, sans-serif;',
      '  color: white;',
      '}',
      '',
      '.front {',
      '  background: #0ea5e9;',
      '}',
      '',
      '.back {',
      '  background: #8b5cf6;',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': [
      '<div class="scene">',
      '  <div class="card">',
      '    <div class="face front">Front</div>',
      '    <div class="face back">Back</div>',
      '  </div>',
      '</div>',
      '',
    ].join('\n'),
    'styles.css': [
      '.scene {',
      '  width: 180px;',
      '  height: 240px;',
      '  perspective: 800px;',
      '}',
      '',
      '.card {',
      '  position: relative;',
      '  width: 100%;',
      '  height: 100%;',
      '  transform-style: preserve-3d;',
      '  transition: transform 600ms ease;',
      '}',
      '',
      '.scene:hover .card {',
      '  transform: rotateY(180deg);',
      '}',
      '',
      '.face {',
      '  position: absolute;',
      '  inset: 0;',
      '  display: grid;',
      '  place-items: center;',
      '  border-radius: 12px;',
      '  backface-visibility: hidden;',
      '  font: 600 18px/1 system-ui, sans-serif;',
      '  color: white;',
      '}',
      '',
      '.front {',
      '  background: #0ea5e9;',
      '}',
      '',
      '.back {',
      '  background: #8b5cf6;',
      '  transform: rotateY(180deg);',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'Four declarations conspire. `perspective` on the *scene* creates the 3D viewpoint (on the parent,',
    'so the whole card shares one vanishing point). `transform-style: preserve-3d` on the *card* stops',
    'the browser flattening its children back to a plane — without it the faces rotate as a painted',
    'texture. `backface-visibility: hidden` makes each face vanish when it turns away, and pre-rotating',
    '`.back` by 180° means "away" for the back is exactly when the front shows, and vice versa.',
    '',
    '### The pre-rotation trick',
    '',
    'The back face is *always* rotated 180° — it never animates. What animates is the card, and the',
    'back simply becomes the face pointing at you once the card passes 90°. Forgetting the',
    'pre-rotation gives mirror-image text on the flipped card; forgetting `backface-visibility` shows',
    'the back through the front the whole time (the starter bug).',
    '',
    '### The series',
    '',
    'This flip returns twice: in pure Tailwind utilities (`tailwind-basics`, where the challenge is',
    'expressing these four declarations as classes) and in motion (`motion-react-basics`, where the',
    'rotation becomes animated state). Same geometry every time — master it here first.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Depth first: `perspective: 800px` on `.scene`, `transform-style: preserve-3d` on `.card`.',
    'The flip is one rule: `.scene:hover .card { transform: rotateY(180deg); }` plus a `transition` on `.card`.',
    'Faces: `backface-visibility: hidden` on `.face`, and `.back` also gets a permanent `transform: rotateY(180deg)`.',
  ],
  series: { id: 'card-flip', label: 'Card flip' },
  relatedIds: ['css-transitions/hover-lift'],
};
