import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'raf-tweening/first-loop',
  title: 'A first rAF loop',
  categoryId: 'raf-tweening',
  difficulty: 'novice',
  tech: ['ts'],
  runtime: 'dom',
  estimatedMinutes: 12,
  tags: ['raf', 'tween', 'game-loop', 'transform'],
  brief: [
    'No CSS transitions, no animation libraries: move the box yourself, one frame at a time.',
    '',
    'In index.ts, drive the box from `translateX(0)` to `translateX(300px)` over 500ms with a',
    '`requestAnimationFrame` loop. Compute progress from the timestamp rAF hands you, clamp it at 1,',
    'write the transform, and stop requesting frames when the tween is done.',
  ].join('\n'),
  goals: [
    'Driven by `requestAnimationFrame`, the box slides from 0 to 300px over 500ms — no CSS transition or animation is involved.',
    'Half-way — 15 frames at 60Hz, 250ms — the box sits at exactly 150px.',
    'The loop clamps progress at 1 and stops: after finishing, the box rests at exactly 300px and stays there.',
    'The movement writes `transform`, never `left`.',
  ],
  starter: {
    'index.html': '<div class="box" aria-hidden="true"></div>\n',
    'styles.css': [
      '.box {',
      '  width: 48px;',
      '  height: 48px;',
      '  border-radius: 8px;',
      '  background: #f97316;',
      '}',
      '',
    ].join('\n'),
    'index.ts': [
      "const box = document.querySelector<HTMLElement>('.box');",
      '',
      '// Drive box.style.transform from translateX(0) to translateX(300px) over 500ms',
      '// with a requestAnimationFrame loop.',
      'void box;',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<div class="box" aria-hidden="true"></div>\n',
    'styles.css': [
      '.box {',
      '  width: 48px;',
      '  height: 48px;',
      '  border-radius: 8px;',
      '  background: #f97316;',
      '}',
      '',
    ].join('\n'),
    'index.ts': [
      "const box = document.querySelector<HTMLElement>('.box');",
      'const DURATION_MS = 500;',
      'const DISTANCE_PX = 300;',
      '',
      'let start: number | null = null;',
      '',
      'function frame(now: number): void {',
      '  if (start === null) start = now;',
      '  const progress = Math.min((now - start) / DURATION_MS, 1);',
      '  if (box) box.style.transform = `translateX(${progress * DISTANCE_PX}px)`;',
      '  if (progress < 1) requestAnimationFrame(frame);',
      '}',
      '',
      'requestAnimationFrame(frame);',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'A tween is three numbers: when it started, how long it lasts, and how far it goes. rAF hands the',
    'loop a timestamp each frame; `(now - start) / DURATION_MS` turns elapsed time into progress 0→1,',
    'and progress times distance is the transform. The first callback only learns the start time —',
    'which is why `start` is captured from the timestamp, never from `Date.now()` outside the loop.',
    '',
    '### The two lines everyone forgets',
    '',
    '`Math.min(progress, 1)` and `if (progress < 1)`. Without the clamp, the last frame overshoots',
    '(frames land ~16.7ms apart, not exactly on 500); without the stop condition the loop runs',
    'forever, burning a frame callback per frame for an animation that finished. Clamp, write the',
    'final value once, stop asking for frames.',
    '',
    '### Why `transform`',
    '',
    'Writing `left` forces layout every frame — the whole page reflows 60 times a second. Writing',
    '`transform` stays on the compositor. Same rule as every CSS challenge in this catalog, and it',
    'matters *more* here because JS-driven movement already competes with everything else on the main',
    'thread.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Skeleton: `function frame(now) { … requestAnimationFrame(frame); } requestAnimationFrame(frame);`',
    'Capture the start from the FIRST timestamp: `if (start === null) start = now;` — then progress is `(now - start) / 500`.',
    'Clamp with `Math.min(progress, 1)`, and only re-request a frame `if (progress < 1)`.',
  ],
  relatedIds: ['easing-math/lerp'],
};
