import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'css-keyframes/bounce-in',
  title: 'Bounce-in entrance',
  categoryId: 'css-keyframes',
  difficulty: 'novice',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 8,
  tags: ['keyframes', 'animation', 'fill-mode', 'overshoot'],
  brief: [
    'The badge just sits there. Give it an entrance.',
    '',
    'Animate it in with a `@keyframes` rule named `bounce-in`: it starts at half size and invisible,',
    'overshoots to 1.1× at the 60% mark, and settles at full size. 500ms, played once, end state held.',
  ].join('\n'),
  goals: [
    'The badge animates in through a `@keyframes` rule named `bounce-in`.',
    'It starts at `scale(0.5)` and `opacity: 0`.',
    'At 60% of the animation the badge reads `scale(1.1)` — the overshoot frame.',
    'The animation runs 500ms, once, and its fill mode holds the end state: `scale(1)`, fully opaque.',
  ],
  starter: {
    'index.html': '<div class="badge">New!</div>\n',
    'styles.css': [
      '.badge {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 96px;',
      '  height: 96px;',
      '  border-radius: 50%;',
      '  background: #0ea5e9;',
      '  color: white;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '}',
      '',
      '/* Declare the bounce-in keyframes and play them on .badge. */',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<div class="badge">New!</div>\n',
    'styles.css': [
      '.badge {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 96px;',
      '  height: 96px;',
      '  border-radius: 50%;',
      '  background: #0ea5e9;',
      '  color: white;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '  animation: bounce-in 500ms ease-out both;',
      '}',
      '',
      '@keyframes bounce-in {',
      '  from {',
      '    transform: scale(0.5);',
      '    opacity: 0;',
      '  }',
      '',
      '  60% {',
      '    transform: scale(1.1);',
      '    opacity: 1;',
      '  }',
      '',
      '  to {',
      '    transform: scale(1);',
      '    opacity: 1;',
      '  }',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'A `@keyframes` rule is a named timeline: `from` is the pre-entrance state, the `60%` frame is the',
    'overshoot, and `to` is rest. The `animation` shorthand on `.badge` binds the timeline to the element',
    'with a duration (500ms) and a fill mode.',
    '',
    '### The overshoot is just a keyframe',
    '',
    'No physics involved: passing *through* `scale(1.1)` on the way to `scale(1)` is what reads as a',
    'bounce. In CSS, `animation-timing-function` applies **between keyframes**, so `ease-out` shapes each',
    'segment — but at the 60% mark the value is exactly `scale(1.1)` regardless of easing.',
    '',
    '### Why `both` matters',
    '',
    'Without a fill mode the badge snaps back to its static styles the instant the animation ends —',
    'the classic "my entrance un-happens" bug. `both` applies the `from` frame before the animation',
    'starts and holds `to` afterwards.',
    '',
    '### The same entrance, two other ways',
    '',
    'This series rebuilds the identical bounce with `element.animate()` (`waapi/bounce-in`, where the',
    'default easing is linear per effect, not per segment) and with a real spring in motion',
    '(`motion-react-basics/bounce-in-spring`, where the overshoot emerges from physics instead of a',
    'hand-placed frame).',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Two pieces: a `@keyframes bounce-in { … }` rule, and an `animation:` shorthand on `.badge` that plays it.',
    'The overshoot is one keyframe: `60% { transform: scale(1.1); }` between `from` and `to`.',
    'If the badge snaps back to full size at the end, you are missing `animation-fill-mode` — `both` (or `forwards`) holds the final frame.',
  ],
  series: { id: 'bounce-in', label: 'Bounce-in entrance' },
  relatedIds: ['waapi/bounce-in', 'motion-react-basics/bounce-in-spring'],
};
