import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'accessibility/reduced-motion-swap',
  title: 'Replace the motion, keep the message',
  categoryId: 'accessibility',
  difficulty: 'novice',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 10,
  tags: ['prefers-reduced-motion', 'accessibility', 'media-query', 'entrance'],
  brief: [
    'The banner slides in from the right — a 320px sweep. For someone with a vestibular disorder,',
    'large translations like that can be physically unpleasant, and they have told the browser so.',
    '',
    'Honour `prefers-reduced-motion: reduce` — but do not simply delete the animation. The banner is',
    'feedback; it still needs an entrance. Swap the slide for a plain fade of the same duration, so',
    'reduced-motion users get the message without the motion.',
  ].join('\n'),
  goals: [
    'By default the banner slides in from 320px to the right of its resting spot, fading in as it arrives, over 500ms.',
    'When `prefers-reduced-motion: reduce` is set, the banner still animates in — a fade of the same 500ms duration.',
    'Under reduced motion the banner never moves horizontally: the motion is replaced, not the feedback deleted.',
  ],
  starter: {
    'index.html': '<div class="banner" role="status">Saved</div>\n',
    'styles.css': [
      '.banner {',
      '  width: 220px;',
      '  padding: 12px 16px;',
      '  border-radius: 10px;',
      '  background: #22c55e;',
      '  color: white;',
      '  font: 600 14px/1.2 system-ui, sans-serif;',
      '  animation: slide-in 500ms ease-out both;',
      '}',
      '',
      '@keyframes slide-in {',
      '  from {',
      '    transform: translateX(320px);',
      '    opacity: 0;',
      '  }',
      '',
      '  to {',
      '    transform: translateX(0);',
      '    opacity: 1;',
      '  }',
      '}',
      '',
      '/* Respect prefers-reduced-motion: reduce — swap the slide for a fade. */',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<div class="banner" role="status">Saved</div>\n',
    'styles.css': [
      '.banner {',
      '  width: 220px;',
      '  padding: 12px 16px;',
      '  border-radius: 10px;',
      '  background: #22c55e;',
      '  color: white;',
      '  font: 600 14px/1.2 system-ui, sans-serif;',
      '  animation: slide-in 500ms ease-out both;',
      '}',
      '',
      '@keyframes slide-in {',
      '  from {',
      '    transform: translateX(320px);',
      '    opacity: 0;',
      '  }',
      '',
      '  to {',
      '    transform: translateX(0);',
      '    opacity: 1;',
      '  }',
      '}',
      '',
      '@keyframes fade-in {',
      '  from {',
      '    opacity: 0;',
      '  }',
      '',
      '  to {',
      '    opacity: 1;',
      '  }',
      '}',
      '',
      '@media (prefers-reduced-motion: reduce) {',
      '  .banner {',
      '    animation-name: fade-in;',
      '  }',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'The media query overrides one longhand — `animation-name` — so the reduced branch inherits the',
    'duration, easing, and fill from the default rule and swaps only the keyframes. The fade has no',
    'transform at all: under reduced motion the banner appears in place.',
    '',
    '### Replace, do not delete',
    '',
    'The lazy fix is `animation: none`, and it is a real accessibility bug of its own: the user asked',
    'for less *motion*, not less *information*. A banner that pops in with no transition at all is',
    'harder to notice — the entrance exists to draw the eye. A fade draws the eye without moving',
    'anything. Reduced motion is a substitution problem, not a deletion problem.',
    '',
    '### What counts as "motion"',
    '',
    'Large translations, parallax, zooms, and spins are the vestibular triggers; opacity and color',
    'are safe. That is why the swap keeps `opacity` and drops `transform`. The same substitution',
    'thinking scales up: the vestibular-safe parallax replacement later in this category is this',
    'challenge at page scale.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Add a second `@keyframes` (a plain fade), then override ONLY `animation-name` inside the media query.',
    'The query is `@media (prefers-reduced-motion: reduce) { … }` — keep it a single clause.',
    'Overriding just `animation-name` keeps the 500ms duration and fill from the default rule — that is the point.',
  ],
  relatedIds: ['css-keyframes/bounce-in'],
};
