import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'scroll-driven/scroll-progress',
  title: 'A scroll-driven progress bar',
  categoryId: 'scroll-driven',
  difficulty: 'intermediate',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 12,
  tags: ['scroll-timeline', 'scroll-driven', 'progress', 'compositor'],
  brief: [
    'A reading-progress bar with zero JavaScript.',
    '',
    'The page below is tall. Pin the `.progress` bar to the top and drive it with a scroll timeline:',
    'a keyframes animation from `scaleX(0)` to `scaleX(1)` whose timeline is `scroll(root)`, so the',
    'bar tracks how far down the page the reader is. Grow it with `transform: scaleX()` from the left',
    'edge — never by animating `width`.',
  ].join('\n'),
  goals: [
    'The bar is driven by a `scroll()` animation timeline — no JavaScript, no scroll listeners.',
    'At the top of the page the bar is at `scaleX(0)`; half-way down it reads about 0.5; at the bottom it spans the full width.',
    'The bar grows with `transform: scaleX()` from the left edge — its `width` never animates.',
  ],
  starter: {
    'index.html': [
      '<div class="progress" aria-hidden="true"></div>',
      '<article class="content">',
      '  <h1>Long read</h1>',
      '  <p>Scroll to see the bar track your progress.</p>',
      '</article>',
      '',
    ].join('\n'),
    'styles.css': [
      '.progress {',
      '  position: fixed;',
      '  top: 0;',
      '  left: 0;',
      '  width: 100%;',
      '  height: 6px;',
      '  background: #38bdf8;',
      '  transform-origin: 0 50%;',
      '  transform: scaleX(0);',
      '}',
      '',
      '/* Animate .progress from scaleX(0) to scaleX(1), driven by scroll(root). */',
      '',
      '.content {',
      '  min-height: 3000px;',
      '  padding: 24px;',
      '  font: 16px/1.6 system-ui, sans-serif;',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': [
      '<div class="progress" aria-hidden="true"></div>',
      '<article class="content">',
      '  <h1>Long read</h1>',
      '  <p>Scroll to see the bar track your progress.</p>',
      '</article>',
      '',
    ].join('\n'),
    'styles.css': [
      '.progress {',
      '  position: fixed;',
      '  top: 0;',
      '  left: 0;',
      '  width: 100%;',
      '  height: 6px;',
      '  background: #38bdf8;',
      '  transform-origin: 0 50%;',
      '  transform: scaleX(0);',
      '  animation: grow-progress auto linear both;',
      '  animation-timeline: scroll(root);',
      '}',
      '',
      '@keyframes grow-progress {',
      '  from {',
      '    transform: scaleX(0);',
      '  }',
      '',
      '  to {',
      '    transform: scaleX(1);',
      '  }',
      '}',
      '',
      '.content {',
      '  min-height: 3000px;',
      '  padding: 24px;',
      '  font: 16px/1.6 system-ui, sans-serif;',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'An `animation-timeline` swaps the clock an animation runs on. `scroll(root)` is a timeline whose',
    '"time" is the root scroller’s progress: 0 at the top, 1 at the bottom. The keyframes are an',
    'ordinary `scaleX(0)` → `scaleX(1)` pair; scrolling scrubs them. `linear` matters — you want the',
    'bar proportional to scroll, not eased — and the `auto` duration lets the timeline’s range',
    'define the animation’s length.',
    '',
    '### Declaration order matters',
    '',
    'The `animation` shorthand resets `animation-timeline` to its default. Write the shorthand first',
    'and `animation-timeline: scroll(root)` after it — reversed, the timeline silently becomes the',
    'document clock and the bar fills in 0 seconds.',
    '',
    '### Why `scaleX`, not `width`',
    '',
    'Scroll-driven animations restyle on every scrolled frame. Animating `width` would relayout the',
    'page per frame; `transform: scaleX()` with `transform-origin: 0 50%` stretches a painted layer',
    'on the compositor — same visual, none of the cost. This is the compositor-property rule from the',
    'CSS challenges, applied where it hurts most.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Keyframes first: `@keyframes grow-progress { from { transform: scaleX(0); } to { transform: scaleX(1); } }`.',
    'Attach them with `animation: grow-progress auto linear both;` and THEN `animation-timeline: scroll(root);` — the shorthand resets the timeline if it comes second.',
    'If the bar is full before you scroll, the timeline line is missing (or above the shorthand) and the animation ran on the normal clock.',
  ],
  relatedIds: [],
};
