import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'motion-react-basics/bounce-in-spring',
  title: 'Bounce-in with a spring',
  categoryId: 'motion-react-basics',
  difficulty: 'novice',
  tech: ['react', 'motion'],
  runtime: 'react',
  estimatedMinutes: 10,
  tags: ['motion', 'react', 'spring', 'initial-animate'],
  graderTimeoutMs: 10_000,
  brief: [
    'Third take on the bounce-in entrance: let a spring do the bouncing.',
    '',
    'Render the badge as a `motion.div` that mounts at half size and transparent, then springs to full',
    'size and opacity. No keyframes and no overshoot frame — pick `stiffness` and `damping` so the',
    'overshoot emerges from the physics.',
  ].join('\n'),
  goals: [
    'The badge mounts at half size and transparent (`initial`), then animates to full size and opacity (`animate`).',
    'The scale overshoots past 1 on the way in — spring physics, not a hand-placed keyframe.',
    'It comes to rest at exactly full size and full opacity.',
    'The spring feels lively: a quick pop that settles within about a second.',
  ],
  starter: {
    'App.tsx': ['export default function App() {', '  return <div className="badge">New!</div>;', '}', ''].join('\n'),
    'styles.css': [
      '.badge {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 96px;',
      '  height: 96px;',
      '  border-radius: 50%;',
      '  background: #0ea5e9;',
      '  color: white;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'App.tsx': [
      "import { motion } from 'motion/react';",
      '',
      'export default function App() {',
      '  return (',
      '    <motion.div',
      '      className="badge"',
      '      initial={{ scale: 0.5, opacity: 0 }}',
      '      animate={{ scale: 1, opacity: 1 }}',
      "      transition={{ type: 'spring', stiffness: 260, damping: 12 }}",
      '    >',
      '      New!',
      '    </motion.div>',
      '  );',
      '}',
      '',
    ].join('\n'),
    'styles.css': [
      '.badge {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 96px;',
      '  height: 96px;',
      '  border-radius: 50%;',
      '  background: #0ea5e9;',
      '  color: white;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    '`initial` is the mounted state, `animate` is the target, and motion animates between them on',
    'mount. With `type: "spring"` the trajectory is simulated physics: stiffness is the pull toward',
    'the target, damping is the friction that stops it. At stiffness 260 / damping 12 the badge is',
    'underdamped — it shoots past scale 1, comes back, and settles. The overshoot the other two',
    'series members hand-authored as a `scale(1.1)` keyframe *emerges* here, and its size changes',
    'when you tune the physics.',
    '',
    '### No duration',
    '',
    'A spring does not take a duration — it takes physics, and runs until it comes to rest. That is',
    'the deep difference from `css-keyframes/bounce-in` and `waapi/bounce-in`, where 500ms was a hard',
    'promise. If you find yourself wanting "a spring that lasts exactly 500ms", motion supports',
    '`duration`/`bounce` as an alternative spring parameterisation — traded for direct control of',
    'stiffness.',
    '',
    '### Reading the numbers',
    '',
    'Lower damping → bigger overshoot and longer wobble. Higher stiffness → faster attack. The',
    'reference values (260/12) pop in and settle in roughly three quarters of a second.',
  ].join('\n'),
  gradeMode: 'hybrid',
  rubric: [
    {
      id: 'lively',
      label: 'The entrance feels lively — a quick pop with a visible bounce, not a slow drift.',
    },
    {
      id: 'settles-clean',
      label: 'It settles cleanly, without lingering vibration after the first bounce or two.',
    },
    {
      id: 'matches-target',
      label: 'Side by side with the target, the spring character feels the same.',
      detail: 'Tune stiffness and damping until the motion — not just the end state — matches.',
    },
  ],
  hints: [
    'Import `{ motion }` from `motion/react` and change the `div` to `motion.div`.',
    'Mount-time entrances are the `initial` + `animate` pair — put the pre-entrance state in `initial`.',
    "The bounce comes from `transition={{ type: 'spring', stiffness: 260, damping: 12 }}` — lower damping, bigger bounce.",
  ],
  series: { id: 'bounce-in', label: 'Bounce-in entrance' },
  relatedIds: ['css-keyframes/bounce-in', 'waapi/bounce-in'],
};
