import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'svg-animation/line-draw',
  title: 'Draw the line',
  categoryId: 'svg-animation',
  difficulty: 'novice',
  tech: ['css', 'svg'],
  runtime: 'dom',
  estimatedMinutes: 10,
  tags: ['svg', 'stroke-dasharray', 'stroke-dashoffset', 'line-drawing'],
  brief: [
    'The classic SVG reveal: a stroke that draws itself tip to tail.',
    '',
    'The path is set up with `pathLength="400"`, so its length is exactly 400 units regardless of',
    'geometry. In styles.css: make the line start invisible with a dash pattern that covers the whole',
    'path and an offset that pushes it out of view, then animate `stroke-dashoffset` to 0 over 900ms',
    'with `ease-in-out`, holding the drawn state at the end.',
  ].join('\n'),
  goals: [
    'The path starts invisible: `stroke-dasharray` covers the whole 400-unit line and `stroke-dashoffset` starts at 400.',
    'A CSS animation pulls `stroke-dashoffset` to 0 over 900ms with `ease-in-out` — half drawn at the halfway point.',
    'The line stays fully drawn when the animation ends (a forwards fill).',
  ],
  starter: {
    'index.html': [
      '<svg viewBox="0 0 200 100" width="200" height="100" role="img" aria-label="A curved line">',
      '  <path',
      '    class="line"',
      '    pathLength="400"',
      '    d="M 10 80 C 60 10, 140 10, 190 80"',
      '    fill="none"',
      '    stroke="#0ea5e9"',
      '    stroke-width="4"',
      '    stroke-linecap="round"',
      '  />',
      '</svg>',
      '',
    ].join('\n'),
    'styles.css': ['/* Hide the line behind its dash pattern, then animate stroke-dashoffset to 0. */', ''].join('\n'),
  },
  solution: {
    'index.html': [
      '<svg viewBox="0 0 200 100" width="200" height="100" role="img" aria-label="A curved line">',
      '  <path',
      '    class="line"',
      '    pathLength="400"',
      '    d="M 10 80 C 60 10, 140 10, 190 80"',
      '    fill="none"',
      '    stroke="#0ea5e9"',
      '    stroke-width="4"',
      '    stroke-linecap="round"',
      '  />',
      '</svg>',
      '',
    ].join('\n'),
    'styles.css': [
      '.line {',
      '  stroke-dasharray: 400;',
      '  stroke-dashoffset: 400;',
      '  animation: draw 900ms ease-in-out forwards;',
      '}',
      '',
      '@keyframes draw {',
      '  to {',
      '    stroke-dashoffset: 0;',
      '  }',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'A dashed stroke is a repeating pattern of dash and gap. `stroke-dasharray: 400` makes both the',
    'dash and the gap as long as the entire path, and `stroke-dashoffset: 400` slides the pattern one',
    'full length backward — so the visible window shows only gap. Animating the offset to 0 slides',
    'the single dash into view from the start of the path: the line "draws".',
    '',
    '### Why `pathLength="400"` matters',
    '',
    'Without it, the dash math needs `getTotalLength()` — a JS call — because the true length of a',
    'curve is awkward to know by hand. `pathLength` renormalises the path to a length you chose, so',
    'the CSS speaks in round numbers and the technique stays JS-free. Change the `d` attribute and',
    'nothing else needs to move.',
    '',
    '### The `to`-only keyframe',
    '',
    'The `@keyframes draw` rule declares only `to`: the `from` state comes from the resting styles.',
    'That is deliberate — one source of truth for the hidden state. And as with every entrance in',
    'this catalog, the fill mode (`forwards`) is what stops the line un-drawing itself when the',
    'animation ends.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Both dash values are the path length: `stroke-dasharray: 400; stroke-dashoffset: 400;` hides everything.',
    'One keyframe is enough: `@keyframes draw { to { stroke-dashoffset: 0; } }` — the from state is the resting style.',
    'The shorthand: `animation: draw 900ms ease-in-out forwards;` — without `forwards` the line vanishes again.',
  ],
  relatedIds: [],
};
