import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'waapi/bounce-in',
  title: 'Bounce-in via WAAPI',
  categoryId: 'waapi',
  difficulty: 'intermediate',
  tech: ['waapi', 'ts'],
  runtime: 'dom',
  estimatedMinutes: 10,
  tags: ['waapi', 'element-animate', 'keyframes', 'fill'],
  brief: [
    'Rebuild the bounce-in entrance from `css-keyframes/bounce-in` — this time entirely in JavaScript',
    'with `element.animate()`. The stylesheet stays static: no `@keyframes` at all.',
    '',
    'Same shape as the CSS version: `scale(0.5)` and transparent at the start, `scale(1.1)` at the 60%',
    'mark, `scale(1)` at the end. 500ms, linear effect easing, `fill: "forwards"`.',
  ].join('\n'),
  goals: [
    'The entrance is built with `element.animate()` — the stylesheet declares no `@keyframes` rule.',
    'The badge starts at half size and fully transparent, and a middle keyframe creates the overshoot.',
    'The effect runs 500ms with linear easing, so at 300ms (offset 0.6) the badge reads exactly `scale(1.1)`.',
    '`fill: "forwards"` holds the end state: after the animation the badge rests at full size, fully opaque.',
  ],
  starter: {
    'index.html': '<div class="badge">New!</div>\n',
    'styles.css': [
      '.badge {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 96px;',
      '  height: 96px;',
      '  border-radius: 50%;',
      '  background: #0ea5e9;',
      '  color: white;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '}',
      '',
    ].join('\n'),
    'index.ts': [
      "const badge = document.querySelector('.badge');",
      '',
      '// Build the bounce-in entrance with badge.animate(keyframes, options).',
      'void badge;',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<div class="badge">New!</div>\n',
    'styles.css': [
      '.badge {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 96px;',
      '  height: 96px;',
      '  border-radius: 50%;',
      '  background: #0ea5e9;',
      '  color: white;',
      '  font: 600 16px/1 system-ui, sans-serif;',
      '}',
      '',
    ].join('\n'),
    'index.ts': [
      "const badge = document.querySelector('.badge');",
      '',
      'if (badge) {',
      '  badge.animate(',
      '    [',
      "      { transform: 'scale(0.5)', opacity: 0 },",
      "      { transform: 'scale(1.1)', opacity: 1, offset: 0.6 },",
      "      { transform: 'scale(1)', opacity: 1 },",
      '    ],',
      "    { duration: 500, easing: 'linear', fill: 'forwards' },",
      '  );',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    '`element.animate(keyframes, options)` builds the same kind of animation object the CSS engine',
    'builds from `@keyframes` — but constructed at runtime, returned to you, and controllable',
    '(`pause()`, `reverse()`, `finished`). The keyframe array maps one-to-one onto the CSS version;',
    '`offset: 0.6` is the WAAPI spelling of the `60%` selector.',
    '',
    '### The easing difference that bites everyone',
    '',
    'CSS applies `animation-timing-function` **between keyframes**; WAAPI applies `easing` from the',
    'options across the **whole effect** by warping iteration progress. The CSS default is `ease`; the',
    "WAAPI default is `linear`. That is why this challenge pins `easing: 'linear'`: with linear effect",
    'easing, 300ms into a 500ms effect is exactly progress 0.6, and the badge reads exactly the 0.6',
    'keyframe. Per-keyframe easing exists in WAAPI too — as an `easing` property *on a keyframe* —',
    'and that is the one that matches CSS semantics.',
    '',
    '### `fill: "forwards"` is `animation-fill-mode`',
    '',
    'Same rule as the CSS version: without a fill the effect stops applying when it finishes and the',
    'badge snaps back. (WAAPI purists later call `commitStyles()` and cancel the animation to move the',
    'end state into the style attribute — that trick has its own challenge in this category.)',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'The keyframe array takes plain objects: `{ transform: "scale(0.5)", opacity: 0 }` first, the rest after.',
    'Place the overshoot frame with an explicit `offset: 0.6` — without it, keyframes distribute evenly.',
    'The options object needs `duration: 500`, `easing: "linear"`, and `fill: "forwards"` so the end state sticks.',
  ],
  series: { id: 'bounce-in', label: 'Bounce-in entrance' },
  relatedIds: ['css-keyframes/bounce-in', 'motion-react-basics/bounce-in-spring'],
};
