import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'css-transitions/hover-lift',
  title: 'Hover lift',
  categoryId: 'css-transitions',
  difficulty: 'novice',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 6,
  tags: ['transition', 'transform', 'compositor'],
  brief: [
    'The card below jumps to its hovered state with no animation.',
    '',
    'Make it rise smoothly on hover: a 200ms lift of 6px with a deeper shadow.',
    'Animate only properties the compositor can handle on its own.',
  ].join('\n'),
  goals: [
    'Hovering the card moves it up by 6px over roughly 200ms.',
    'The shadow deepens over the same period.',
    'Only transform and opacity-backed properties are transitioned — no `all`, no `top`, no `margin`.',
  ],
  starter: {
    'index.html': '<div class="card">Hover me</div>\n',
    'styles.css': [
      '.card {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 220px;',
      '  height: 120px;',
      '  border-radius: 12px;',
      '  background: white;',
      '  box-shadow: 0 1px 2px rgb(0 0 0 / 0.08);',
      '}',
      '',
      '.card:hover {',
      '  /* Make this animate. */',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<div class="card">Hover me</div>\n',
    'styles.css': [
      '.card {',
      '  display: grid;',
      '  place-items: center;',
      '  width: 220px;',
      '  height: 120px;',
      '  border-radius: 12px;',
      '  background: white;',
      '  box-shadow: 0 1px 2px rgb(0 0 0 / 0.08);',
      '  transition:',
      '    transform 200ms cubic-bezier(0.2, 0, 0, 1),',
      '    box-shadow 200ms cubic-bezier(0.2, 0, 0, 1);',
      '}',
      '',
      '.card:hover {',
      '  transform: translateY(-6px);',
      '  box-shadow: 0 12px 24px rgb(0 0 0 / 0.16);',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    '`transform` is one of the two properties (with `opacity`) a browser can animate entirely on the',
    'compositor thread. Moving the card with `translateY` never triggers layout or paint, so the',
    'animation survives a busy main thread.',
    '',
    '### Why not `top` or `margin-top`',
    '',
    'Both change geometry, so every frame costs a layout pass for the card and potentially its siblings.',
    'The result looks identical when the page is idle and janks the moment it is not.',
    '',
    '### Why not `transition: all`',
    '',
    '`all` transitions every animatable property that happens to change, including ones you never intended',
    'and ones added later. It is a standing invitation to accidental animation, and it costs style',
    'recalculation on properties you do not care about. Name the properties.',
    '',
    '### The shadow caveat',
    '',
    '`box-shadow` is *not* compositor-friendly — it repaints each frame. At this size it is fine, but',
    'the cheaper pattern for large or frequently animated shadows is a pseudo-element holding the deeper',
    'shadow, with only its `opacity` transitioned. That technique gets its own challenge in the',
    'performance category.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'The `transition` property belongs on the resting state, not only on `:hover` — otherwise the return trip is instant.',
    'Which two properties can a browser animate without touching layout or paint?',
    'List the transitioned properties explicitly, separated by commas.',
  ],
  relatedIds: [],
};
