import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'easing-timing/overshoot-bezier',
  title: 'Overshoot from a cubic-bezier',
  categoryId: 'easing-timing',
  difficulty: 'intermediate',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 10,
  tags: ['easing', 'cubic-bezier', 'overshoot', 'transition'],
  brief: [
    'The chip already slides on hover — but it lands flat. Make it overshoot.',
    '',
    'Keep the single transition (160px over 400ms), and replace `ease` with a `cubic-bezier()` whose',
    'output control values push above 1 — for example `cubic-bezier(0.34, 1.56, 0.64, 1)`. The chip',
    'should travel past its destination and settle back, with no keyframes involved.',
  ].join('\n'),
  goals: [
    'Hovering slides the chip 160px right over 400ms, landing exactly on target.',
    'Mid-flight it travels past 160px and comes back — overshoot created purely by the transition easing, not extra keyframes.',
    'The timing function is a custom `cubic-bezier()` with at least one output (y) control value greater than 1.',
  ],
  starter: {
    'index.html': '<button type="button" class="chip">Slide</button>\n',
    'styles.css': [
      '.chip {',
      '  width: 120px;',
      '  padding: 12px 0;',
      '  text-align: center;',
      '  border: 0;',
      '  border-radius: 9999px;',
      '  background: #a78bfa;',
      '  font: 600 14px/1 system-ui, sans-serif;',
      '  transition: transform 400ms ease;',
      '}',
      '',
      '.chip:hover {',
      '  transform: translateX(160px);',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<button type="button" class="chip">Slide</button>\n',
    'styles.css': [
      '.chip {',
      '  width: 120px;',
      '  padding: 12px 0;',
      '  text-align: center;',
      '  border: 0;',
      '  border-radius: 9999px;',
      '  background: #a78bfa;',
      '  font: 600 14px/1 system-ui, sans-serif;',
      '  transition: transform 400ms cubic-bezier(0.34, 1.56, 0.64, 1);',
      '}',
      '',
      '.chip:hover {',
      '  transform: translateX(160px);',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'A transition interpolates progress 0→1 through its timing function. Nothing forbids the curve',
    'from *leaving* that range: `cubic-bezier(0.34, 1.56, 0.64, 1)` has its first output control at',
    '1.56, so mid-transition the eased progress exceeds 1 — the chip is briefly past 160px — before',
    'the curve comes back down to land at exactly 1. The x control values must stay in [0, 1] (they',
    'are time), but the y values are free.',
    '',
    '### Overshoot without keyframes',
    '',
    'The keyframe version of this effect (see `css-keyframes/bounce-in`) hand-places a `scale(1.1)`',
    'frame. The easing version needs no extra state: it composes with ANY property change, reverses',
    'cleanly when the hover ends, and retargets smoothly when interrupted — because it is still just',
    'one transition.',
    '',
    '### Reading the curve',
    '',
    'In `cubic-bezier(x1, y1, x2, y2)`, y1 > 1 means "overshoot early, glide back"; y2 > 1 pushes the',
    'overshoot late. Values below 0 anticipate (pull back before launching). Tools like',
    'cubic-bezier.com let you drag the handles and watch — the reference value here is a mild 10%',
    'overshoot.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Only the timing function changes — the starter already has the right property, distance, and duration.',
    'In `cubic-bezier(x1, y1, x2, y2)` the two y values are the output curve: push one above 1.',
    'Try `cubic-bezier(0.34, 1.56, 0.64, 1)` and then tune: bigger y1, bigger bounce.',
  ],
  relatedIds: ['css-keyframes/bounce-in'],
};
