import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'easing-timing/snappy-ease',
  title: 'A snappier ease',
  categoryId: 'easing-timing',
  difficulty: 'novice',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 5,
  tags: ['easing', 'cubic-bezier', 'feel'],
  brief: [
    'The chip lifts on hover with the default `ease` — serviceable, but sluggish: `ease` spends its',
    'first moments accelerating, so the response feels late.',
    '',
    'Replace `ease` with a `cubic-bezier()` you tune yourself so the response starts fast and',
    'decelerates into place. The reference uses `cubic-bezier(0.2, 0, 0, 1)` — a material-style',
    '"standard decelerate" — but this is a feel exercise: match the target side by side.',
  ].join('\n'),
  goals: [
    'The hover response starts fast: the curve front-loads velocity instead of easing in.',
    'It decelerates smoothly into the final state with no overshoot.',
    'The default `ease` keyword is replaced by an explicit `cubic-bezier()` tuned by hand.',
  ],
  starter: {
    'index.html': '<button type="button" class="chip">Save</button>\n',
    'styles.css': [
      '.chip {',
      '  padding: 12px 24px;',
      '  border: 0;',
      '  border-radius: 9999px;',
      '  background: #34d399;',
      '  font: 600 14px/1 system-ui, sans-serif;',
      '  transition: transform 250ms ease;',
      '}',
      '',
      '.chip:hover {',
      '  transform: translateY(-4px) scale(1.03);',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<button type="button" class="chip">Save</button>\n',
    'styles.css': [
      '.chip {',
      '  padding: 12px 24px;',
      '  border: 0;',
      '  border-radius: 9999px;',
      '  background: #34d399;',
      '  font: 600 14px/1 system-ui, sans-serif;',
      '  transition: transform 250ms cubic-bezier(0.2, 0, 0, 1);',
      '}',
      '',
      '.chip:hover {',
      '  transform: translateY(-4px) scale(1.03);',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    '`cubic-bezier(0.2, 0, 0, 1)` reaches high velocity almost immediately (small x1, zero y1 means',
    'the curve leaves the origin steeply) and spends most of its 250ms decelerating (x2 of 0, y2 of 1',
    'flattens the approach). The default `ease` — `cubic-bezier(0.25, 0.1, 0.25, 1)` — accelerates',
    'first, which reads as a pause before the response.',
    '',
    '### Why this is graded by eye',
    '',
    '"Snappier" is a perceptual claim. A machine can verify that you changed the curve, but not that',
    'the result *feels* right — the difference between 0.2 and 0.35 for x1 is taste, context, and',
    'distance. This is what the rubric grade mode exists for (spec §2): run yours beside the target,',
    'hover both, and judge the first 100ms honestly.',
    '',
    '### A rule of thumb worth keeping',
    '',
    'Interfaces respond to the user; they do not wind up. Enter fast and land soft (decelerate) for',
    'responses to user intent; ease in only when something leaves on its own schedule.',
  ].join('\n'),
  gradeMode: 'rubric',
  rubric: [
    {
      id: 'starts-fast',
      label: 'The movement visibly starts faster than the starter version.',
      detail: 'Hover both panes together and watch the first 100ms — the tuned curve should already be moving.',
    },
    {
      id: 'no-overshoot',
      label: 'It settles without bouncing past its end position.',
    },
    {
      id: 'matches-target',
      label: 'Side by side with the target, both feel equally snappy.',
    },
  ],
  hints: [
    'Only the timing function changes — keep the property, distance, and 250ms duration.',
    'Front-load velocity with a small x1 and y1 (try 0.2 and 0); land soft with x2 near 0 and y2 at 1.',
    'Compare against the target with quick hover-in/hover-out flicks, not long stares.',
  ],
  relatedIds: ['easing-timing/overshoot-bezier'],
};
