import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'spring-physics/spring-step',
  title: 'A fixed-timestep spring integrator',
  categoryId: 'spring-physics',
  difficulty: 'intermediate',
  tech: ['ts'],
  runtime: 'module',
  estimatedMinutes: 15,
  tags: ['spring', 'integrator', 'physics', 'semi-implicit-euler'],
  brief: [
    'Simulate a damped spring one timestep at a time.',
    '',
    'Implement `springStep(state, config, dtSeconds)`: from the current `{ position, velocity }`,',
    'compute the spring force (`-stiffness × displacement`) and damping force (`-damping × velocity`),',
    'derive acceleration (`force / mass`), then integrate **semi-implicitly**: update velocity first,',
    'then update position using the NEW velocity. Return a fresh state object — never mutate the input.',
  ].join('\n'),
  goals: [
    'One step updates velocity first, then position from the NEW velocity (semi-implicit Euler): from rest at 0 toward target 1 with stiffness 100, damping 10, mass 1, dt 1/60, one step lands at exactly position 1/36 and velocity 5/3.',
    '`springStep` never mutates the state it is given — it returns a fresh `{ position, velocity }`.',
    'Stepped repeatedly at dt 1/60, a stiffness 170 / damping 26 / mass 1 spring converges on its target and comes to rest.',
    'With damping lowered to 8 the spring overshoots its target before settling — underdamped behaviour emerges from the maths.',
  ],
  starter: {
    'index.ts': [
      'export interface SpringState {',
      '  position: number;',
      '  velocity: number;',
      '}',
      '',
      'export interface SpringConfig {',
      '  target: number;',
      '  stiffness: number;',
      '  damping: number;',
      '  mass: number;',
      '}',
      '',
      'export function springStep(state: SpringState, config: SpringConfig, dtSeconds: number): SpringState {',
      '  // Forces: spring pulls toward the target, damping resists velocity.',
      '  // Integrate semi-implicitly: velocity first, then position from the NEW velocity.',
      '  return { position: state.position, velocity: state.velocity };',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.ts': [
      'export interface SpringState {',
      '  position: number;',
      '  velocity: number;',
      '}',
      '',
      'export interface SpringConfig {',
      '  target: number;',
      '  stiffness: number;',
      '  damping: number;',
      '  mass: number;',
      '}',
      '',
      'export function springStep(state: SpringState, config: SpringConfig, dtSeconds: number): SpringState {',
      '  const displacement = state.position - config.target;',
      '  const springForce = -config.stiffness * displacement;',
      '  const dampingForce = -config.damping * state.velocity;',
      '  const acceleration = (springForce + dampingForce) / config.mass;',
      '  const velocity = state.velocity + acceleration * dtSeconds;',
      '  const position = state.position + velocity * dtSeconds;',
      '  return { position, velocity };',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    "Hooke's law plus friction: the spring force is proportional to how far you are from the target",
    '(and points back toward it); damping is proportional to how fast you are moving (and opposes it).',
    'Dividing by mass turns force into acceleration, and then integration is just "velocity collects',
    'acceleration, position collects velocity".',
    '',
    '### Why semi-implicit Euler',
    '',
    'The order of those two updates matters more than it looks. *Explicit* Euler (position first,',
    'using the OLD velocity) systematically injects energy: at high stiffness the simulated spring',
    'gains amplitude every bounce and eventually explodes. Updating velocity first and reusing it for',
    'position (*semi-implicit*, or symplectic, Euler) slightly removes energy instead — the',
    'simulation stays stable at the stiffness values UI springs actually use. Every production',
    'animation library integrates springs this way. The first goal pins the order numerically: from',
    'rest, explicit Euler moves position 0 on the first step (old velocity is 0); semi-implicit moves',
    'it by `newVelocity × dt`.',
    '',
    '### Rest, overshoot, and what "done" means',
    '',
    'With damping 26 (near critical for stiffness 170) the spring glides in and stops. Drop damping',
    'to 8 and it is underdamped: it crosses the target, comes back, and rings down. Detecting "done"',
    '(position near target AND velocity near zero) is its own challenge later in this category.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Displacement is `position - target`; the spring force is `-stiffness * displacement`.',
    'Acceleration is `(springForce + dampingForce) / mass`; damping force is `-damping * velocity`.',
    'Order matters: `velocity += acceleration * dt` FIRST, then `position += velocity * dt` with the new velocity.',
  ],
  series: { id: 'spring-settle', label: 'Spring settle' },
  relatedIds: ['easing-math/lerp'],
};
