import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'motion-core/first-animate',
  title: 'animate() an element',
  categoryId: 'motion-core',
  difficulty: 'novice',
  tech: ['motion', 'ts'],
  runtime: 'dom',
  estimatedMinutes: 6,
  tags: ['motion', 'animate', 'waapi', 'vanilla'],
  brief: [
    "One import, one call: use motion's `animate()` to slide the box 240px to the right.",
    '',
    'Duration 1.2 seconds (motion counts in seconds, not milliseconds), `easeOut` easing. Compare the',
    'ergonomics with the rAF loop you may have hand-written in `raf-tweening/first-loop` — this is',
    'the same tween, delegated.',
  ].join('\n'),
  goals: [
    "The box is animated by motion's `animate()`, which drives a real Web Animation — it starts at 0 and lands exactly on `translateX(240px)`.",
    'The effect runs 1.2 seconds and eases out: at half time the box is already well past half distance.',
    'The end state sticks — after the animation the box rests at 240px.',
  ],
  starter: {
    'index.html': '<div class="box" aria-hidden="true"></div>\n',
    'styles.css': [
      '.box {',
      '  width: 48px;',
      '  height: 48px;',
      '  border-radius: 8px;',
      '  background: #14b8a6;',
      '}',
      '',
    ].join('\n'),
    'index.ts': [
      "// import { animate } from 'motion' and slide .box 240px right over 1.2s, easing out.",
      'export {};',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': '<div class="box" aria-hidden="true"></div>\n',
    'styles.css': [
      '.box {',
      '  width: 48px;',
      '  height: 48px;',
      '  border-radius: 8px;',
      '  background: #14b8a6;',
      '}',
      '',
    ].join('\n'),
    'index.ts': [
      "import { animate } from 'motion';",
      '',
      "animate('.box', { transform: 'translateX(240px)' }, { duration: 1.2, ease: 'easeOut' });",
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    "motion's vanilla `animate()` takes a target (an element, or a selector it resolves for you),",
    'the values to animate to, and options. For transform values it hands the work to the Web',
    'Animations API — the browser runs the animation off the main thread where it can — and returns',
    'playback controls. Compare `raf-tweening/first-loop`: the loop, the clamp, the stop condition,',
    'the easing math — all of it is this one call.',
    '',
    '### Seconds, not milliseconds',
    '',
    'motion counts time in seconds (`duration: 1.2`), unlike CSS and WAAPI (milliseconds). Mixing the',
    'two conventions is the most common first bug when adopting motion — a `duration: 300` tween',
    'lasts five minutes.',
    '',
    '### What "delegated" buys you',
    '',
    'Because the underlying animation is a real WAAPI object, devtools sees it, `document',
    '.getAnimations()` lists it, and it keeps running while the main thread is busy. A hand-rolled',
    'rAF loop gets none of that for free — which is why the later challenges in this category are',
    "about motion's sequencing and controls, not about reimplementing tweens.",
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    "The import is `import { animate } from 'motion';` — the sandbox resolves `motion` for you.",
    "`animate('.box', { transform: 'translateX(240px)' }, { … })` — a selector string works as the target.",
    "Options: `{ duration: 1.2, ease: 'easeOut' }`. Seconds! `duration: 1200` would run for 20 minutes.",
  ],
  relatedIds: ['raf-tweening/first-loop', 'waapi/bounce-in'],
};
