import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'interruption-state/reversible-hover',
  title: 'Reversible hover',
  categoryId: 'interruption-state',
  difficulty: 'intermediate',
  tech: ['css'],
  runtime: 'dom',
  estimatedMinutes: 10,
  tags: ['transition', 'interruption', 'reversal', 'hover'],
  brief: [
    'Hover the track: the knob glides right. Leave — and it teleports home. Users flick pointers',
    'across interfaces constantly; every flick across this track snaps.',
    '',
    'The starter declares its `transition` inside the `:hover` rule, so the transition only exists',
    'while hovered. Fix the placement so both directions animate — and so that leaving mid-flight',
    'reverses smoothly from wherever the knob currently is.',
  ].join('\n'),
  goals: [
    'Hovering the track slides the knob 120px right over 600ms (linear), and leaving hover animates it back — both directions transition.',
    'Interrupted mid-flight, the knob reverses from exactly where it is: the return transition starts at the interruption point, never snapping to either end.',
    'The knob moves with `transform` only — never `left` or `margin`.',
  ],
  starter: {
    'index.html': ['<div class="track">', '  <div class="knob" aria-hidden="true"></div>', '</div>', ''].join('\n'),
    'styles.css': [
      '.track {',
      '  display: flex;',
      '  align-items: center;',
      '  width: 180px;',
      '  height: 44px;',
      '  padding: 4px;',
      '  border-radius: 9999px;',
      '  background: #e2e8f0;',
      '}',
      '',
      '.knob {',
      '  width: 36px;',
      '  height: 36px;',
      '  border-radius: 50%;',
      '  background: #0f172a;',
      '}',
      '',
      '.track:hover .knob {',
      '  transform: translateX(120px);',
      '  transition: transform 600ms linear;',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': ['<div class="track">', '  <div class="knob" aria-hidden="true"></div>', '</div>', ''].join('\n'),
    'styles.css': [
      '.track {',
      '  display: flex;',
      '  align-items: center;',
      '  width: 180px;',
      '  height: 44px;',
      '  padding: 4px;',
      '  border-radius: 9999px;',
      '  background: #e2e8f0;',
      '}',
      '',
      '.knob {',
      '  width: 36px;',
      '  height: 36px;',
      '  border-radius: 50%;',
      '  background: #0f172a;',
      '  transition: transform 600ms linear;',
      '}',
      '',
      '.track:hover .knob {',
      '  transform: translateX(120px);',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'A transition applies when the *destination* state has one. Declared only inside `:hover`, it',
    'exists on the way in (destination: hovered) and vanishes on the way out (destination: resting,',
    'which has no `transition`) — so the return snaps. Moving the declaration to the resting `.knob`',
    'rule puts it on both destinations: in animates, out animates.',
    '',
    '### Interruption is free — if the transition lives in the right place',
    '',
    'CSS transitions retarget: when the hover ends mid-flight, the browser starts the new transition',
    'from the *current computed value*, not from the hover endpoint. There is no state to manage and',
    'no JS to write — the smooth mid-flight reversal falls out of correct declaration placement.',
    '(The browser even shortens the return duration proportionally, so a 10%-progressed slide does',
    'not take the full 600ms to undo.)',
    '',
    '### The pattern to remember',
    '',
    'Transitions on the base rule, state changes in the state rules. Every interruptible interaction',
    'in this category — and the expert-level velocity handoffs later — builds on this placement rule.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'Watch what changes between the starter rules: WHERE the `transition` line lives is the whole bug.',
    'Transitions belong on the resting `.knob` rule; the `:hover` rule should only change `transform`.',
    'To test by hand: flick the pointer off the track mid-slide — the knob should turn around in place.',
  ],
  relatedIds: ['css-transitions/hover-lift'],
};
