import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'easing-math/lerp',
  title: 'lerp and inverseLerp',
  categoryId: 'easing-math',
  difficulty: 'novice',
  tech: ['ts'],
  runtime: 'module',
  estimatedMinutes: 8,
  tags: ['interpolation', 'math', 'pure-functions'],
  brief: [
    'Every tween, spring, and scroll-linked effect is built on one idea: blending between two numbers.',
    '',
    'Implement the two directions of that idea:',
    '',
    '- `lerp(a, b, t)` — the value a fraction `t` of the way from `a` to `b`.',
    '- `inverseLerp(a, b, value)` — the fraction at which `value` sits between `a` and `b`.',
    '',
    'Keep both functions pure, and do not clamp: callers decide whether extrapolation is wanted.',
  ].join('\n'),
  goals: [
    '`lerp(a, b, t)` returns the value a fraction `t` of the way from `a` to `b` — `lerp(10, 20, 0.5)` is `15`, and negative ranges work.',
    '`inverseLerp(a, b, value)` inverts it — `inverseLerp(10, 20, 15)` is `0.5` — so `inverseLerp(a, b, lerp(a, b, t))` round-trips to `t`.',
    'Neither function clamps: `lerp(0, 10, 1.5)` is `15`, and `inverseLerp(0, 10, -5)` is `-0.5`.',
  ],
  starter: {
    'index.ts': [
      'export function lerp(a: number, b: number, t: number): number {',
      '  // Blend a toward b by the fraction t.',
      '  return a;',
      '}',
      '',
      'export function inverseLerp(a: number, b: number, value: number): number {',
      '  // At what fraction does value sit between a and b?',
      '  return 0;',
      '}',
      '',
    ].join('\n'),
  },
  solution: {
    'index.ts': [
      'export function lerp(a: number, b: number, t: number): number {',
      '  return a + (b - a) * t;',
      '}',
      '',
      'export function inverseLerp(a: number, b: number, value: number): number {',
      '  return (value - a) / (b - a);',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    '`a + (b - a) * t` is the whole trick: at `t = 0` the second term vanishes, at `t = 1` it is the',
    'full distance, and in between it is a proportional slice. `inverseLerp` solves the same equation',
    'for `t`. Every easing function you will write later is just a reshaping of `t` before it hits',
    'this line.',
    '',
    '### Why no clamping',
    '',
    'Clamping inside `lerp` looks helpful and quietly breaks two real uses: springs overshoot their',
    'target (`t > 1` is the overshoot), and scroll-linked values often extrapolate past their design',
    'range on rubber-band scrolls. Compose clamping *around* the primitive when a caller wants it —',
    'the range-remapping challenge later in this category does exactly that.',
    '',
    '### The `t` mental model',
    '',
    'Read `t` as "progress", not "time": `inverseLerp` converts a raw value (a scroll offset, an',
    'elapsed time) into progress, and `lerp` converts progress into an output value. Chaining them —',
    'remap — is the backbone of scroll-driven animation.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'One line each: start at `a`, add the fraction `t` of the distance `b - a`.',
    'For the inverse, ask: how far is `value` from `a`, as a share of the whole distance?',
    'If your round-trip test fails, one of the two divides or multiplies by the wrong distance.',
  ],
  relatedIds: [],
};
