import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'tailwind-custom/theme-pulse',
  title: 'A @theme animation token',
  categoryId: 'tailwind-custom',
  difficulty: 'intermediate',
  tech: ['tailwind', 'css'],
  runtime: 'dom',
  estimatedMinutes: 12,
  tags: ['tailwind', 'theme', 'keyframes', 'design-tokens'],
  brief: [
    'The markup already asks for `animate-pulse-ring` — but Tailwind v4 only generates an',
    '`animate-*` utility when a matching `--animate-*` token exists in the theme.',
    '',
    'In `theme.css`, declare a `@theme` block with an `--animate-pulse-ring` token — value',
    '`pulse-ring 1200ms ease-in-out infinite` — and define the `pulse-ring` keyframes inside the same',
    '`@theme` block: at 0% and 100% the dot is normal; at 50% it is scaled to 1.25 with opacity 0.6.',
  ].join('\n'),
  goals: [
    'A `@theme` block declares `--animate-pulse-ring`, so Tailwind generates both the `animate-pulse-ring` utility and its `pulse-ring` keyframes.',
    'The dot pulses forever: 1200ms per cycle with `ease-in-out`.',
    'At the midpoint of each cycle the dot reaches 1.25× scale and 0.6 opacity, and it is back to normal at the cycle boundary.',
  ],
  starter: {
    'index.html': '<div class="dot animate-pulse-ring size-6 rounded-full bg-sky-500" aria-hidden="true"></div>\n',
    'theme.css': ['/* Declare the --animate-pulse-ring token (and its keyframes) inside a @theme block. */', ''].join(
      '\n',
    ),
  },
  solution: {
    'index.html': '<div class="dot animate-pulse-ring size-6 rounded-full bg-sky-500" aria-hidden="true"></div>\n',
    'theme.css': [
      '@theme {',
      '  --animate-pulse-ring: pulse-ring 1200ms ease-in-out infinite;',
      '',
      '  @keyframes pulse-ring {',
      '    0%,',
      '    100% {',
      '      transform: scale(1);',
      '      opacity: 1;',
      '    }',
      '',
      '    50% {',
      '      transform: scale(1.25);',
      '      opacity: 0.6;',
      '    }',
      '  }',
      '}',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'Tailwind v4 has no JS config: the theme IS CSS. A `--animate-<name>` token inside `@theme` does',
    'two things at once — it defines the design token, and it teaches the compiler to generate an',
    '`animate-<name>` utility whose value is the token. Keyframes declared inside `@theme` ride along:',
    'they are emitted into the output only when some utility actually references them, which is why',
    'the starter — same markup, no token — renders a motionless dot.',
    '',
    '### Token first, utility second',
    '',
    'The failure mode this challenge teaches: writing `animate-pulse-ring` in markup and expecting it',
    'to work. Utilities are *generated from* theme tokens; an unknown `animate-*` class compiles to',
    'nothing at all (not even an error). When an animation utility does nothing, check the theme.',
    '',
    '### Why keyframes live in the theme here',
    '',
    'They could sit at top level of the stylesheet — but inside `@theme` they are tree-shaken with the',
    'token and shared by anything else that references `--animate-pulse-ring`, which is exactly how a',
    'design system wants animation tokens to behave.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'The shape is `@theme { --animate-pulse-ring: pulse-ring 1200ms ease-in-out infinite; }` — the value is a full `animation` shorthand.',
    'Define `@keyframes pulse-ring` INSIDE the same `@theme` block; group `0%, 100%` for the resting frames.',
    'If the dot still does not move, the token name and the utility must match exactly: `--animate-pulse-ring` ↔ `animate-pulse-ring`.',
  ],
  relatedIds: ['tailwind-basics/hover-transition'],
};
