import type { Challenge } from '@/challenges/types';

export const challenge: Challenge = {
  id: 'tailwind-basics/hover-transition',
  title: 'Hover transition utilities',
  categoryId: 'tailwind-basics',
  difficulty: 'novice',
  tech: ['tailwind', 'css'],
  runtime: 'dom',
  estimatedMinutes: 6,
  tags: ['tailwind', 'transition', 'hover', 'utilities'],
  brief: [
    'The same hover lift you may have built in raw CSS — this time speaking Tailwind.',
    '',
    'Make the card rise 6px on hover with a smooth 300ms ease-out transition, using only utility',
    'classes in the markup: `transition-transform`, `duration-300`, `ease-out`, and a `hover:`',
    'translate variant.',
  ].join('\n'),
  goals: [
    'Hovering lifts the card 6px (`hover:-translate-y-1.5`), and the movement animates rather than teleporting.',
    'The transition targets the transform utilities specifically (`transition-transform`) — never `transition-all`.',
    'It runs for 300ms with the decelerating `ease-out` curve.',
  ],
  starter: {
    'index.html': [
      '<button type="button" class="card rounded-xl bg-white px-6 py-4 font-medium shadow">',
      '  Hover me',
      '</button>',
      '',
    ].join('\n'),
  },
  solution: {
    'index.html': [
      '<button',
      '  type="button"',
      '  class="card rounded-xl bg-white px-6 py-4 font-medium shadow transition-transform duration-300 ease-out hover:-translate-y-1.5"',
      '>',
      '  Hover me',
      '</button>',
      '',
    ].join('\n'),
  },
  explanation: [
    '### Why this works',
    '',
    'Four utilities carry the whole behaviour. `hover:-translate-y-1.5` is the state change (−6px:',
    'Tailwind spacing is a 4px scale, so 1.5 × 4 = 6). `transition-transform` opts the transform',
    'family into transitioning; `duration-300` and `ease-out` shape it. Remove any one and you get a',
    'teleport, a wrong speed, or a linear feel.',
    '',
    '### Why `transition-transform`, not `transition-all`',
    '',
    'Same reasoning as the raw-CSS version (`css-transitions/hover-lift`): `transition-all` animates',
    'every property that ever changes on the element — including ones a later utility adds by',
    'accident. Naming the family keeps the transition intentional and cheap.',
    '',
    '### What Tailwind actually emits',
    '',
    'There is no magic: each utility compiles to one declaration — `transition-property`,',
    '`transition-duration`, `transition-timing-function`, and a translate on the `:hover` variant.',
    'Open devtools and read the generated rules; the CSS challenge and this one produce near-identical',
    'computed styles. Tailwind is a notation for the same engine.',
  ].join('\n'),
  gradeMode: 'auto',
  hints: [
    'The state change is a variant: `hover:-translate-y-1.5` (negative = up; 1.5 steps × 4px = 6px).',
    'A state change without `transition-transform` teleports — the transition utilities live on the resting element.',
    'Speed and feel are `duration-300` and `ease-out`.',
  ],
  relatedIds: ['css-transitions/hover-lift'],
};
